language: c

compiler: gcc
env: BUILD=autotools

matrix:
  include:
    - compiler: gcc
      env: BUILD=autotools USE_BINARY_DATA=no
    - compiler: clang
      env: BUILD=autotools
    - compiler: gcc
      env: BUILD=cmake

script:
  - if [ x$BUILD == xautotools -a x$USE_BINARY_DATA != xno ]; then ./autogen.sh && ./configure && make && make check; fi
  - if [ x$BUILD == xautotools -a x$USE_BINARY_DATA == xno ]; then ./autogen.sh && ./configure --disable-binary-data && make && make check; fi
  - if [ x$BUILD == xcmake ]; then cmake . && make && make test; fi

before_install:
  - sudo add-apt-repository --yes ppa:czchen/travis-ci # For cmake 2.8.9
  - sudo apt-get update -qq
  - sudo apt-get install -qq texinfo cmake valgrind
