status = [
    "build (ubuntu-latest, WITH_RUST=ON)",
    "build (ubuntu-latest, WITH_RUST=OFF)",
    "build (windows-latest, WITH_RUST=ON)",
    "build (windows-latest, WITH_RUST=OFF)",
    "build (macos-latest, WITH_RUST=ON)",
    "build (macos-latest, WITH_RUST=OFF)",
    "cargo_test (ubuntu-latest)",
    "cargo_test (windows-latest)",
    "cargo_test (macos-latest)",
    "build_with_hash",
]