[package]
name = "chewing"
description = "The Chewing (酷音) intelligent Zhuyin input method."
license = "LGPL-2.1-or-later"
documentation = "https://docs.rs/chewing"
version = "0.5.1-alpha.1"
edition = "2021"

[dependencies]
thiserror = "1.0.0"

[dev-dependencies]

[workspace]
members = ["capi/chewing-internal", "capi/chewing-public"]

[profile.release]
lto = "thin"
