[package]
name = "chewing"
description = "The Chewing (酷音) intelligent Zhuyin input method."
license = "LGPL-2.1-or-later"
documentation = "https://docs.rs/chewing"
version = "0.5.1-alpha.2"
edition = "2021"

include = [
    "src/**/*.rs",
    "Cargo.toml",
    "AUTHORS",
    "COPYING",
    "NEWS"
]

[dependencies]
bytemuck = { version = "1.13.0", features = ["derive"] }
dirs-next = "2.0.0"
indexmap = "1.9.2"
riff = "1.0.0"
rusqlite = "0.28.0"
thiserror = "1.0.0"
tracing = "0.1.37"

[target.'cfg(windows)'.dependencies]
rusqlite = { version = "0.28.0", features = ["bundled"]}

[dev-dependencies]
tempfile = "3"

[workspace]
members = ["capi/chewing-internal", "capi/chewing-public", "tools"]

[profile.release]
lto = true
debug = true