[package]
name = "chewing"
description = "The Chewing (酷音) intelligent Zhuyin input method."
license = "LGPL-2.1-or-later"
documentation = "https://docs.rs/chewing"
version = "0.6.0-alpha.1"
rust-version = "1.70"
edition = "2021"

include = ["src/**/*.rs", "Cargo.toml", "AUTHORS", "COPYING", "NEWS"]

[dependencies]
bytemuck = { version = "1.14.0", features = ["derive"] }
directories = "5.0.0"
indexmap = "2.1.0"
riff = "2.0.0"
rusqlite = "0.30.0"
thiserror = "1.0.0"
tracing = "0.1.40"

[target.'cfg(windows)'.dependencies]
rusqlite = { version = "0.30.0", features = ["bundled"] }

[lib]
crate-type = ["lib", "staticlib"]

[features]
default = []
capi = ["cbindgen"]

[build-dependencies]
# https://github.com/mozilla/cbindgen/issues/891
cbindgen = { version = "0.24.5", optional = true }

[dev-dependencies]
tempfile = "3"

[workspace]
members = ["tools", "xtask"]

[profile.release]
lto = true
debug = true
