[package]
name = "chewing"
description = "The Chewing (酷音) intelligent Zhuyin input method."
license = "LGPL-2.1-or-later"
documentation = "https://docs.rs/chewing"
version = "0.6.0-alpha.1"
rust-version = "1.70"
edition = "2021"

include = ["src/**/*.rs", "data/*", "Cargo.toml", "AUTHORS", "COPYING", "NEWS"]

[dependencies]
bytemuck = { version = "1.14.0", features = ["derive"] }
cdb2 = { version = "0.7.0-alpha.1" }
directories = "5.0.0"
riff = "2.0.0"
rusqlite = { version = "0.30.0", optional = true }
thiserror = "1.0.0"
tracing = { version = "0.1.40", features = [
    "max_level_trace",
    "release_max_level_warn",
] }
tracing-subscriber = { version = "0.3.18", features = [
    "env-filter",
], optional = true }

[target.'cfg(windows)'.dependencies]
rusqlite = { version = "0.30.0", features = ["bundled"], optional = true }

[lib]
crate-type = ["rlib", "staticlib"]

[features]
default = []
capi = []
sqlite = ["rusqlite"]
test-tracing = ["tracing-subscriber"]

[dev-dependencies]
tempfile = "3"

[workspace]
members = ["tools", "xtask"]
resolver = "2"

[profile.release]
lto = true
debug = true
panic = "abort"
