[package]
name = "fuzzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chewing = { version = "0.6.0-alpha.2", path = "..", features = ["capi"] }
env_logger = "0.11.3"
xflags = "0.3.2"
