
# cargo-vet audits file

[[wildcard-audits.cdb2]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-deploy"
user-id = 7551 # Kan-Ru Chen (kanru)
start = "2024-01-06"
end = "2025-03-30"

[[wildcard-audits.chewing]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-deploy"
user-id = 7551 # Kan-Ru Chen (kanru)
start = "2022-05-07"
end = "2025-03-30"

[[wildcard-audits.chewing-cli]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-deploy"
user-id = 7551 # Kan-Ru Chen (kanru)
start = "2024-03-26"
end = "2025-03-30"

[[audits.allocator-api2]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-deploy"
delta = "0.2.16 -> 0.2.18"

[[audits.cc]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-deploy"
delta = "1.0.90 -> 1.0.95"

[[audits.der]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-deploy"
version = "0.7.9"

[[audits.fastrand]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-run"
delta = "2.0.2 -> 2.1.0"

[[audits.getrandom]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-deploy"
delta = "0.2.12 -> 0.2.13"

[[audits.libredox]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-deploy"
delta = "0.0.1 -> 0.1.3"

[[audits.log]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-deploy"
delta = "0.4.20 -> 0.4.21"

[[audits.proc-macro2]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-deploy"
delta = "1.0.80 -> 1.0.81"

[[audits.redox_users]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-deploy"
delta = "0.4.4 -> 0.4.5"

[[audits.windows_i686_gnullvm]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-run"
version = "0.52.5"

[[audits.xflags]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-deploy"
version = "0.3.2"

[[audits.xflags-macros]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-deploy"
version = "0.3.2"

[[audits.zeroize]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-deploy"
version = "1.7.0"

[[trusted.aho-corasick]]
criteria = "safe-to-deploy"
user-id = 189
start = "2019-03-28"
end = "2025-03-30"

[[trusted.anyhow]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-10-05"
end = "2025-03-30"

[[trusted.cc]]
criteria = "safe-to-deploy"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2024-02-20"
end = "2025-03-30"

[[trusted.hashbrown]]
criteria = "safe-to-deploy"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2019-04-02"
end = "2025-03-30"

[[trusted.is-terminal]]
criteria = "safe-to-deploy"
user-id = 6825 # Dan Gohman (sunfishcode)
start = "2022-01-22"
end = "2025-03-30"

[[trusted.libc]]
criteria = "safe-to-deploy"
user-id = 51017 # Yuki Okushi (JohnTitor)
start = "2020-03-17"
end = "2025-03-30"

[[trusted.linux-raw-sys]]
criteria = "safe-to-deploy"
user-id = 6825 # Dan Gohman (sunfishcode)
start = "2021-06-12"
end = "2025-03-30"

[[trusted.memchr]]
criteria = "safe-to-deploy"
user-id = 189
start = "2019-07-07"
end = "2025-03-30"

[[trusted.regex]]
criteria = "safe-to-deploy"
user-id = 189
start = "2019-02-27"
end = "2025-03-30"

[[trusted.regex-automata]]
criteria = "safe-to-deploy"
user-id = 189
start = "2019-02-25"
end = "2025-03-30"

[[trusted.regex-syntax]]
criteria = "safe-to-deploy"
user-id = 189
start = "2019-03-30"
end = "2025-03-30"

[[trusted.rustix]]
criteria = "safe-to-deploy"
user-id = 6825 # Dan Gohman (sunfishcode)
start = "2021-10-29"
end = "2025-03-30"

[[trusted.smallvec]]
criteria = "safe-to-deploy"
user-id = 2017 # Matt Brubeck (mbrubeck)
start = "2019-10-28"
end = "2025-03-30"

[[trusted.syn]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2025-03-30"

[[trusted.termcolor]]
criteria = "safe-to-deploy"
user-id = 189
start = "2019-06-04"
end = "2025-03-30"

[[trusted.thiserror]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-10-09"
end = "2025-03-30"

[[trusted.thiserror-impl]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-10-09"
end = "2025-03-30"

[[trusted.winapi-util]]
criteria = "safe-to-deploy"
user-id = 189
start = "2020-01-11"
end = "2025-03-30"

[[trusted.windows-sys]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-11-15"
end = "2025-03-30"

[[trusted.windows-targets]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-09"
end = "2025-03-30"

[[trusted.windows_aarch64_gnullvm]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-01"
end = "2025-03-30"

[[trusted.windows_aarch64_msvc]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-11-05"
end = "2025-03-30"

[[trusted.windows_i686_gnu]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-28"
end = "2025-03-30"

[[trusted.windows_i686_msvc]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-27"
end = "2025-03-30"

[[trusted.windows_x86_64_gnu]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-28"
end = "2025-03-30"

[[trusted.windows_x86_64_gnullvm]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-01"
end = "2025-03-30"

[[trusted.windows_x86_64_msvc]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-27"
end = "2025-03-30"
