
# cargo-vet audits file

[[wildcard-audits.cdb2]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-deploy"
user-id = 7551 # Kan-Ru Chen (kanru)
start = "2024-01-06"
end = "2025-03-30"

[[wildcard-audits.chewing]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-deploy"
user-id = 7551 # Kan-Ru Chen (kanru)
start = "2022-05-07"
end = "2025-03-30"

[[wildcard-audits.chewing-cli]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-deploy"
user-id = 7551 # Kan-Ru Chen (kanru)
start = "2024-03-26"
end = "2025-03-30"

[[audits.allocator-api2]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-deploy"
delta = "0.2.16 -> 0.2.18"

[[audits.cc]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-deploy"
delta = "1.0.90 -> 1.0.95"

[[audits.cc]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-deploy"
delta = "1.0.95 -> 1.0.96"

[[audits.cc]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-deploy"
delta = "1.0.96 -> 1.0.97"

[[audits.der]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-deploy"
version = "0.7.9"

[[audits.der]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-deploy"
delta = "0.7.9 -> 0.7.7"

[[audits.fallible-iterator]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-deploy"
delta = "0.3.0 -> 0.2.0"

[[audits.fastrand]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-run"
delta = "2.0.2 -> 2.1.0"

[[audits.getrandom]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-deploy"
delta = "0.2.12 -> 0.2.13"

[[audits.hashlink]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-deploy"
delta = "0.9.0 -> 0.8.4"

[[audits.libredox]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-deploy"
delta = "0.0.1 -> 0.1.3"

[[audits.log]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-deploy"
delta = "0.4.20 -> 0.4.21"

[[audits.proc-macro2]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-deploy"
delta = "1.0.80 -> 1.0.81"

[[audits.proc-macro2]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-deploy"
delta = "1.0.81 -> 1.0.82"

[[audits.redox_users]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-deploy"
delta = "0.4.4 -> 0.4.5"

[[audits.rusqlite]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-deploy"
delta = "0.31.0 -> 0.29.0"

[[audits.windows_i686_gnullvm]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-run"
version = "0.52.5"

[[audits.xflags]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-deploy"
version = "0.3.2"

[[audits.xflags-macros]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-deploy"
version = "0.3.2"

[[audits.zerocopy]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-deploy"
delta = "0.7.32 -> 0.7.34"

[[audits.zerocopy-derive]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-deploy"
delta = "0.7.32 -> 0.7.34"

[[audits.zeroize]]
who = "Kan-Ru Chen <kanru@kanru.info>"
criteria = "safe-to-deploy"
version = "1.7.0"

[[trusted.aho-corasick]]
criteria = "safe-to-deploy"
user-id = 189
start = "2019-03-28"
end = "2025-03-30"

[[trusted.anstream]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-03-16"
end = "2025-05-02"

[[trusted.anstyle]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2022-05-18"
end = "2025-05-02"

[[trusted.anstyle-parse]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-03-08"
end = "2025-05-02"

[[trusted.anstyle-query]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-04-13"
end = "2025-05-02"

[[trusted.anstyle-wincon]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-03-08"
end = "2025-05-02"

[[trusted.anyhow]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-10-05"
end = "2025-03-30"

[[trusted.cc]]
criteria = "safe-to-deploy"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2024-02-20"
end = "2025-03-30"

[[trusted.clap]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2021-12-08"
end = "2025-05-02"

[[trusted.clap_builder]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-03-28"
end = "2025-05-02"

[[trusted.clap_derive]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2021-12-08"
end = "2025-05-02"

[[trusted.clap_lex]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2022-04-15"
end = "2025-05-02"

[[trusted.clap_mangen]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2022-02-08"
end = "2025-05-02"

[[trusted.colorchoice]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-04-13"
end = "2025-05-02"

[[trusted.env_logger]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2022-11-24"
end = "2025-05-02"

[[trusted.errno]]
criteria = "safe-to-deploy"
user-id = 6825 # Dan Gohman (sunfishcode)
start = "2023-08-29"
end = "2025-05-13"

[[trusted.hashbrown]]
criteria = "safe-to-deploy"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2019-04-02"
end = "2025-03-30"

[[trusted.is-terminal]]
criteria = "safe-to-deploy"
user-id = 6825 # Dan Gohman (sunfishcode)
start = "2022-01-22"
end = "2025-03-30"

[[trusted.is_terminal_polyfill]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2024-05-02"
end = "2025-05-13"

[[trusted.libc]]
criteria = "safe-to-deploy"
user-id = 51017 # Yuki Okushi (JohnTitor)
start = "2020-03-17"
end = "2025-03-30"

[[trusted.libsqlite3-sys]]
criteria = "safe-to-deploy"
user-id = 5062 # gwenn (gwenn)
start = "2019-03-10"
end = "2025-05-13"

[[trusted.linux-raw-sys]]
criteria = "safe-to-deploy"
user-id = 6825 # Dan Gohman (sunfishcode)
start = "2021-06-12"
end = "2025-03-30"

[[trusted.memchr]]
criteria = "safe-to-deploy"
user-id = 189
start = "2019-07-07"
end = "2025-03-30"

[[trusted.regex]]
criteria = "safe-to-deploy"
user-id = 189
start = "2019-02-27"
end = "2025-03-30"

[[trusted.regex-automata]]
criteria = "safe-to-deploy"
user-id = 189
start = "2019-02-25"
end = "2025-03-30"

[[trusted.regex-syntax]]
criteria = "safe-to-deploy"
user-id = 189
start = "2019-03-30"
end = "2025-03-30"

[[trusted.roff]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2021-12-23"
end = "2025-05-02"

[[trusted.rustix]]
criteria = "safe-to-deploy"
user-id = 6825 # Dan Gohman (sunfishcode)
start = "2021-10-29"
end = "2025-03-30"

[[trusted.smallvec]]
criteria = "safe-to-deploy"
user-id = 2017 # Matt Brubeck (mbrubeck)
start = "2019-10-28"
end = "2025-03-30"

[[trusted.syn]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2025-03-30"

[[trusted.termcolor]]
criteria = "safe-to-deploy"
user-id = 189
start = "2019-06-04"
end = "2025-03-30"

[[trusted.thiserror]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-10-09"
end = "2025-03-30"

[[trusted.thiserror-impl]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-10-09"
end = "2025-03-30"

[[trusted.winapi-util]]
criteria = "safe-to-deploy"
user-id = 189
start = "2020-01-11"
end = "2025-03-30"

[[trusted.windows-sys]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-11-15"
end = "2025-03-30"

[[trusted.windows-targets]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-09"
end = "2025-03-30"

[[trusted.windows_aarch64_gnullvm]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-01"
end = "2025-03-30"

[[trusted.windows_aarch64_msvc]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-11-05"
end = "2025-03-30"

[[trusted.windows_i686_gnu]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-28"
end = "2025-03-30"

[[trusted.windows_i686_gnullvm]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2024-04-02"
end = "2025-05-02"

[[trusted.windows_i686_msvc]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-27"
end = "2025-03-30"

[[trusted.windows_x86_64_gnu]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-28"
end = "2025-03-30"

[[trusted.windows_x86_64_gnullvm]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-01"
end = "2025-03-30"

[[trusted.windows_x86_64_msvc]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-27"
end = "2025-03-30"
