
# cargo-vet config file

[cargo-vet]
version = "0.9"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[policy.chewing]
audit-as-crates-io = true

[policy.chewing-cli]
audit-as-crates-io = true

[policy.chewing_testhelper]
criteria = "safe-to-run"

[policy.fuzzer]
criteria = "safe-to-run"

[[exemptions.ahash]]
version = "0.8.11"
criteria = "safe-to-deploy"

[[exemptions.allocator-api2]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.directories]]
version = "5.0.1"
criteria = "safe-to-deploy"

[[exemptions.dirs-sys]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.fallible-iterator]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.fallible-streaming-iterator]]
version = "0.1.9"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.12"
criteria = "safe-to-deploy"

[[exemptions.hashlink]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.libredox]]
version = "0.0.1"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.19.0"
criteria = "safe-to-deploy"

[[exemptions.option-ext]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.pkg-config]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.redox_users]]
version = "0.4.4"
criteria = "safe-to-deploy"

[[exemptions.rusqlite]]
version = "0.31.0"
criteria = "safe-to-deploy"

[[exemptions.vcpkg]]
version = "0.2.15"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"
