
# cargo-vet config file

[cargo-vet]
version = "0.9"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[policy.chewing]
audit-as-crates-io = true

[policy.chewing-cli]
audit-as-crates-io = true

[policy.fuzzer]
criteria = "safe-to-run"

[policy.chewing_testhelper]
criteria = "safe-to-run"

[[exemptions.afl]]
version = "0.15.4"
criteria = "safe-to-run"

[[exemptions.ahash]]
version = "0.8.11"
criteria = "safe-to-deploy"

[[exemptions.aho-corasick]]
version = "1.1.3"
criteria = "safe-to-deploy"

[[exemptions.allocator-api2]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.anyhow]]
version = "1.0.81"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.0.90"
criteria = "safe-to-deploy"

[[exemptions.cdb2]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.chewing]]
version = "0.7.0-beta.1"
criteria = "safe-to-deploy"

[[exemptions.chewing-cli]]
version = "0.7.0-beta.1"
criteria = "safe-to-deploy"

[[exemptions.directories]]
version = "5.0.1"
criteria = "safe-to-deploy"

[[exemptions.dirs-sys]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.env_logger]]
version = "0.10.2"
criteria = "safe-to-deploy"

[[exemptions.errno]]
version = "0.3.8"
criteria = "safe-to-run"

[[exemptions.fallible-iterator]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.fallible-streaming-iterator]]
version = "0.1.9"
criteria = "safe-to-deploy"

[[exemptions.fastrand]]
version = "2.0.2"
criteria = "safe-to-run"

[[exemptions.getrandom]]
version = "0.2.12"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.14.3"
criteria = "safe-to-deploy"

[[exemptions.hashlink]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.home]]
version = "0.5.9"
criteria = "safe-to-run"

[[exemptions.humantime]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.is-terminal]]
version = "0.4.12"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.153"
criteria = "safe-to-deploy"

[[exemptions.libredox]]
version = "0.0.1"
criteria = "safe-to-deploy"

[[exemptions.libsqlite3-sys]]
version = "0.28.0"
criteria = "safe-to-deploy"

[[exemptions.linux-raw-sys]]
version = "0.4.13"
criteria = "safe-to-run"

[[exemptions.log]]
version = "0.4.21"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.7.2"
criteria = "safe-to-deploy"

[[exemptions.memmap2]]
version = "0.9.4"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.19.0"
criteria = "safe-to-deploy"

[[exemptions.option-ext]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.pkg-config]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.redox_users]]
version = "0.4.4"
criteria = "safe-to-deploy"

[[exemptions.regex]]
version = "1.10.4"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.4.6"
criteria = "safe-to-deploy"

[[exemptions.regex-syntax]]
version = "0.8.3"
criteria = "safe-to-deploy"

[[exemptions.riff]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.rusqlite]]
version = "0.31.0"
criteria = "safe-to-deploy"

[[exemptions.rustix]]
version = "0.38.32"
criteria = "safe-to-run"

[[exemptions.smallvec]]
version = "1.13.2"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.55"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.10.1"
criteria = "safe-to-run"

[[exemptions.termcolor]]
version = "1.4.1"
criteria = "safe-to-deploy"

[[exemptions.thiserror]]
version = "1.0.58"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "1.0.58"
criteria = "safe-to-deploy"

[[exemptions.vcpkg]]
version = "0.2.15"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-util]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.52.0"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.52.4"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.52.4"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.52.4"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.52.4"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.52.4"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.52.4"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.52.4"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.52.4"
criteria = "safe-to-deploy"

[[exemptions.xdg]]
version = "2.5.2"
criteria = "safe-to-run"

[[exemptions.xflags]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.xflags-macros]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.7.32"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.7.32"
criteria = "safe-to-deploy"
