[package]
name = "chewing-cli"
description = "Tools of the Chewing (酷音) intelligent Zhuyin input method."
license = "LGPL-2.1-or-later"
version = "0.6.0-alpha.1"
edition = "2021"

[dependencies]
chewing = { version = "0.6.0-alpha.1", path = "..", features = ["sqlite"] }
anyhow = "1.0.0"
xflags = "0.3.2"

[target.'cfg(windows)'.dependencies]
rusqlite = { version = "0.30.0", features = ["bundled"] }
