name: Continuous Integration

on:
  push:
    branches: [ "master", "staging", "trying" ]
  pull_request:
    branches: [ "master" ]
  merge_group:
    types: [checks_requested]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        with_rust: ['WITH_RUST=ON', 'WITH_RUST=OFF']
        rust_version: ['1.64', 'stable']
        exclude:
          - with_rust: 'WITH_RUST=OFF'
            rust_version: 'stable'
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Setup rustup
      run: |
        rustup default ${{ matrix.rust_version }}
        rustup update

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -D${{matrix.with_rust}}

    - name: Show config
      run: cmake -B ${{github.workspace}}/build -LA

    - name: Build
      run: cmake --build ${{github.workspace}}/build -v --config ${{env.BUILD_TYPE}}

    - name: CTest
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure

  cargo_test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust_version: ['1.64', 'stable']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Setup rustup
      run: |
        rustup default ${{ matrix.rust_version }}
        rustup update

    - name: Test
      run: cargo test

  build_with_hash:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DWITH_SQLITE3=OFF

    - name: Show config
      run: cmake -B ${{github.workspace}}/build -LA

    - name: Build
      run: cmake --build ${{github.workspace}}/build -v --config ${{env.BUILD_TYPE}}

    - name: CTest
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
